//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Anchor Link</summary>
	[PublishedContentModel("anchorLink")]
	public partial class AnchorLink : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "anchorLink";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public AnchorLink(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AnchorLink, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Display Name
		///</summary>
		[ImplementPropertyType("displayName")]
		public string DisplayName
		{
			get { return this.GetPropertyValue<string>("displayName"); }
		}

		///<summary>
		/// Element Id
		///</summary>
		[ImplementPropertyType("elementId")]
		public string ElementId
		{
			get { return this.GetPropertyValue<string>("elementId"); }
		}

		///<summary>
		/// Highlighted?
		///</summary>
		[ImplementPropertyType("highlighted")]
		public bool Highlighted
		{
			get { return this.GetPropertyValue<bool>("highlighted"); }
		}

		///<summary>
		/// Link: Link to page rather than element on page
		///</summary>
		[ImplementPropertyType("link")]
		public Umbraco.Web.Models.RelatedLinks Link
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("link"); }
		}
	}
}
