//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Announcement</summary>
	[PublishedContentModel("announcement")]
	public partial class Announcement : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "announcement";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Announcement(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Announcement, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Body
		///</summary>
		[ImplementPropertyType("body")]
		public IHtmlString Body
		{
			get { return this.GetPropertyValue<IHtmlString>("body"); }
		}

		///<summary>
		/// Date of Announcement
		///</summary>
		[ImplementPropertyType("dateOfAnnouncement")]
		public DateTime DateOfAnnouncement
		{
			get { return this.GetPropertyValue<DateTime>("dateOfAnnouncement"); }
		}

		///<summary>
		/// Featured
		///</summary>
		[ImplementPropertyType("featured")]
		public bool Featured
		{
			get { return this.GetPropertyValue<bool>("featured"); }
		}

		///<summary>
		/// List Description
		///</summary>
		[ImplementPropertyType("listDescription")]
		public string ListDescription
		{
			get { return this.GetPropertyValue<string>("listDescription"); }
		}

		///<summary>
		/// List Image
		///</summary>
		[ImplementPropertyType("listImage")]
		public IPublishedContent ListImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("listImage"); }
		}

		///<summary>
		/// List Title
		///</summary>
		[ImplementPropertyType("listTitle")]
		public string ListTitle
		{
			get { return this.GetPropertyValue<string>("listTitle"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}
	}
}
