//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Component--Spacer</summary>
	[PublishedContentModel("componentSpacer")]
	public partial class ComponentSpacer : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "componentSpacer";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ComponentSpacer(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ComponentSpacer, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// CSS Classes
		///</summary>
		[ImplementPropertyType("cssClasses")]
		public string CssClasses
		{
			get { return this.GetPropertyValue<string>("cssClasses"); }
		}

		///<summary>
		/// CSS Id
		///</summary>
		[ImplementPropertyType("cssId")]
		public string CssId
		{
			get { return this.GetPropertyValue<string>("cssId"); }
		}

		///<summary>
		/// Height: (px)
		///</summary>
		[ImplementPropertyType("height")]
		public string Height
		{
			get { return this.GetPropertyValue<string>("height"); }
		}

		///<summary>
		/// Width: (px or %)
		///</summary>
		[ImplementPropertyType("width")]
		public string Width
		{
			get { return this.GetPropertyValue<string>("width"); }
		}
	}
}
