//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Component--Image</summary>
	[PublishedContentModel("componentImage")]
	public partial class ComponentImage : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "componentImage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ComponentImage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ComponentImage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Alt Text
		///</summary>
		[ImplementPropertyType("altText")]
		public string AltText
		{
			get { return this.GetPropertyValue<string>("altText"); }
		}

		///<summary>
		/// Background Image
		///</summary>
		[ImplementPropertyType("backgroundImage")]
		public bool BackgroundImage
		{
			get { return this.GetPropertyValue<bool>("backgroundImage"); }
		}

		///<summary>
		/// Background Size
		///</summary>
		[ImplementPropertyType("backgroundSize")]
		public string BackgroundSize
		{
			get { return this.GetPropertyValue<string>("backgroundSize"); }
		}

		///<summary>
		/// Enable Parallax
		///</summary>
		[ImplementPropertyType("enableParallax")]
		public bool EnableParallax
		{
			get { return this.GetPropertyValue<bool>("enableParallax"); }
		}

		///<summary>
		/// Extra classes
		///</summary>
		[ImplementPropertyType("extraClasses")]
		public string ExtraClasses
		{
			get { return this.GetPropertyValue<string>("extraClasses"); }
		}

		///<summary>
		/// Height
		///</summary>
		[ImplementPropertyType("height")]
		public string Height
		{
			get { return this.GetPropertyValue<string>("height"); }
		}

		///<summary>
		/// Image
		///</summary>
		[ImplementPropertyType("image")]
		public IPublishedContent Image
		{
			get { return this.GetPropertyValue<IPublishedContent>("image"); }
		}

		///<summary>
		/// Link
		///</summary>
		[ImplementPropertyType("link")]
		public Umbraco.Web.Models.RelatedLinks Link
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("link"); }
		}

		///<summary>
		/// Load Lazily
		///</summary>
		[ImplementPropertyType("loadLazily")]
		public bool LoadLazily
		{
			get { return this.GetPropertyValue<bool>("loadLazily"); }
		}
	}
}
