//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Component--Highlight</summary>
	[PublishedContentModel("componentHighlight")]
	public partial class ComponentHighlight : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "componentHighlight";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ComponentHighlight(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ComponentHighlight, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public string Description
		{
			get { return this.GetPropertyValue<string>("description"); }
		}

		///<summary>
		/// Description Text Color
		///</summary>
		[ImplementPropertyType("descriptionTextColor")]
		public string DescriptionTextColor
		{
			get { return this.GetPropertyValue<string>("descriptionTextColor"); }
		}

		///<summary>
		/// Highlight Background Color
		///</summary>
		[ImplementPropertyType("highlightBackgroundColor")]
		public string HighlightBackgroundColor
		{
			get { return this.GetPropertyValue<string>("highlightBackgroundColor"); }
		}

		///<summary>
		/// Highlight Large Text
		///</summary>
		[ImplementPropertyType("highlightLargeText")]
		public string HighlightLargeText
		{
			get { return this.GetPropertyValue<string>("highlightLargeText"); }
		}

		///<summary>
		/// Highlight Small Text
		///</summary>
		[ImplementPropertyType("highlightSmallText")]
		public string HighlightSmallText
		{
			get { return this.GetPropertyValue<string>("highlightSmallText"); }
		}

		///<summary>
		/// Highlight Text Color
		///</summary>
		[ImplementPropertyType("highlightTextColor")]
		public string HighlightTextColor
		{
			get { return this.GetPropertyValue<string>("highlightTextColor"); }
		}

		///<summary>
		/// Hover Highlight Color
		///</summary>
		[ImplementPropertyType("hoverHighlightColor")]
		public string HoverHighlightColor
		{
			get { return this.GetPropertyValue<string>("hoverHighlightColor"); }
		}

		///<summary>
		/// Hover Secondary Color
		///</summary>
		[ImplementPropertyType("hoverSecondaryColor")]
		public string HoverSecondaryColor
		{
			get { return this.GetPropertyValue<string>("hoverSecondaryColor"); }
		}

		///<summary>
		/// Image
		///</summary>
		[ImplementPropertyType("image")]
		public IPublishedContent Image
		{
			get { return this.GetPropertyValue<IPublishedContent>("image"); }
		}

		///<summary>
		/// Image on Right
		///</summary>
		[ImplementPropertyType("imageOnRight")]
		public bool ImageOnRight
		{
			get { return this.GetPropertyValue<bool>("imageOnRight"); }
		}

		///<summary>
		/// More Information Link
		///</summary>
		[ImplementPropertyType("moreInformationLink")]
		public Umbraco.Web.Models.RelatedLinks MoreInformationLink
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("moreInformationLink"); }
		}
	}
}
