//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Component--BackgroundPattern</summary>
	[PublishedContentModel("componentBackgroundPattern")]
	public partial class ComponentBackgroundPattern : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "componentBackgroundPattern";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ComponentBackgroundPattern(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ComponentBackgroundPattern, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Height
		///</summary>
		[ImplementPropertyType("height")]
		public string Height
		{
			get { return this.GetPropertyValue<string>("height"); }
		}

		///<summary>
		/// Pattern: A pattern image to be repeated in the background
		///</summary>
		[ImplementPropertyType("pattern")]
		public IPublishedContent Pattern
		{
			get { return this.GetPropertyValue<IPublishedContent>("pattern"); }
		}

		///<summary>
		/// Top Margin: Spacing above component (can be negative)
		///</summary>
		[ImplementPropertyType("topMargin")]
		public string TopMargin
		{
			get { return this.GetPropertyValue<string>("topMargin"); }
		}
	}
}
