//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Detail Page</summary>
	[PublishedContentModel("detailPage")]
	public partial class DetailPage : PublishedContentModel, IBasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "detailPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public DetailPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<DetailPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Category
		///</summary>
		[ImplementPropertyType("category")]
		public string Category
		{
			get { return this.GetPropertyValue<string>("category"); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public IHtmlString Description
		{
			get { return this.GetPropertyValue<IHtmlString>("description"); }
		}

		///<summary>
		/// File Download
		///</summary>
		[ImplementPropertyType("fileDownload")]
		public IPublishedContent FileDownload
		{
			get { return this.GetPropertyValue<IPublishedContent>("fileDownload"); }
		}

		///<summary>
		/// Image
		///</summary>
		[ImplementPropertyType("image")]
		public IPublishedContent Image
		{
			get { return this.GetPropertyValue<IPublishedContent>("image"); }
		}

		///<summary>
		/// Leasing Contacts
		///</summary>
		[ImplementPropertyType("leasingContacts")]
		public IPublishedContent LeasingContacts
		{
			get { return this.GetPropertyValue<IPublishedContent>("leasingContacts"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}

		///<summary>
		/// Video: Replaces Image
		///</summary>
		[ImplementPropertyType("video")]
		public IPublishedContent Video
		{
			get { return this.GetPropertyValue<IPublishedContent>("video"); }
		}

		///<summary>
		/// Video Image Placeholder
		///</summary>
		[ImplementPropertyType("videoImagePlaceholder")]
		public IPublishedContent VideoImagePlaceholder
		{
			get { return this.GetPropertyValue<IPublishedContent>("videoImagePlaceholder"); }
		}

		///<summary>
		/// Metadata Description
		///</summary>
		[ImplementPropertyType("metadataDescription")]
		public string MetadataDescription
		{
			get { return Umbraco.Web.PublishedContentModels.BasePage.GetMetadataDescription(this); }
		}

		///<summary>
		/// SEO Title
		///</summary>
		[ImplementPropertyType("sEOTitle")]
		public string SEotitle
		{
			get { return Umbraco.Web.PublishedContentModels.BasePage.GetSEotitle(this); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("test")]
		public string Test
		{
			get { return Umbraco.Web.PublishedContentModels.BasePage.GetTest(this); }
		}

		///<summary>
		/// Theme
		///</summary>
		[ImplementPropertyType("theme")]
		public IPublishedContent Theme
		{
			get { return Umbraco.Web.PublishedContentModels.BasePage.GetTheme(this); }
		}
	}
}
