//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Footer</summary>
	[PublishedContentModel("footer")]
	public partial class Footer : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "footer";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Footer(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Footer, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Background Color: Any css color (rgb, hex, name)
		///</summary>
		[ImplementPropertyType("backgroundColor")]
		public string BackgroundColor
		{
			get { return this.GetPropertyValue<string>("backgroundColor"); }
		}

		///<summary>
		/// Components
		///</summary>
		[ImplementPropertyType("components")]
		public IEnumerable<IPublishedContent> Components
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("components"); }
		}

		///<summary>
		/// Social Icons Color: Any css color (rgb, hex, name)
		///</summary>
		[ImplementPropertyType("socialIconsColor")]
		public string SocialIconsColor
		{
			get { return this.GetPropertyValue<string>("socialIconsColor"); }
		}

		///<summary>
		/// Text Color: Any css color (rgb, hex, name)
		///</summary>
		[ImplementPropertyType("textColor")]
		public string TextColor
		{
			get { return this.GetPropertyValue<string>("textColor"); }
		}
	}
}
