//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Image Info Style--Home Page</summary>
	[PublishedContentModel("imageInfoStyleHomePage")]
	public partial class ImageInfoStyleHomePage : ImageInfoStyle
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "imageInfoStyleHomePage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ImageInfoStyleHomePage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ImageInfoStyleHomePage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Background Color
		///</summary>
		[ImplementPropertyType("backgroundColor")]
		public string BackgroundColor
		{
			get { return this.GetPropertyValue<string>("backgroundColor"); }
		}

		///<summary>
		/// Hover Background Color
		///</summary>
		[ImplementPropertyType("hoverBackgroundColor")]
		public string HoverBackgroundColor
		{
			get { return this.GetPropertyValue<string>("hoverBackgroundColor"); }
		}
	}
}
