//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>ImageInfoStyle--PresidentsBox</summary>
	[PublishedContentModel("imageInfoStylePresidentsBox")]
	public partial class ImageInfoStylePresidentsBox : ImageInfoStyle
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "imageInfoStylePresidentsBox";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ImageInfoStylePresidentsBox(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ImageInfoStylePresidentsBox, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Details Background Color
		///</summary>
		[ImplementPropertyType("detailsBackgroundColor")]
		public string DetailsBackgroundColor
		{
			get { return this.GetPropertyValue<string>("detailsBackgroundColor"); }
		}

		///<summary>
		/// Details Text Color
		///</summary>
		[ImplementPropertyType("detailsTextColor")]
		public string DetailsTextColor
		{
			get { return this.GetPropertyValue<string>("detailsTextColor"); }
		}

		///<summary>
		/// Details Text Header Color
		///</summary>
		[ImplementPropertyType("detailsTextHeaderColor")]
		public string DetailsTextHeaderColor
		{
			get { return this.GetPropertyValue<string>("detailsTextHeaderColor"); }
		}

		///<summary>
		/// Highlight Background Color
		///</summary>
		[ImplementPropertyType("highlightBackgroundColor")]
		public string HighlightBackgroundColor
		{
			get { return this.GetPropertyValue<string>("highlightBackgroundColor"); }
		}
	}
}
