//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Image Info Style--Detail Box</summary>
	[PublishedContentModel("imageInfoStyleDetailBox")]
	public partial class ImageInfoStyleDetailBox : ImageInfoStyle
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "imageInfoStyleDetailBox";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ImageInfoStyleDetailBox(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ImageInfoStyleDetailBox, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Header Color
		///</summary>
		[ImplementPropertyType("headerColor")]
		public string HeaderColor
		{
			get { return this.GetPropertyValue<string>("headerColor"); }
		}

		///<summary>
		/// Height
		///</summary>
		[ImplementPropertyType("height")]
		public string Height
		{
			get { return this.GetPropertyValue<string>("height"); }
		}

		///<summary>
		/// Image Width
		///</summary>
		[ImplementPropertyType("imageWidth")]
		public string ImageWidth
		{
			get { return this.GetPropertyValue<string>("imageWidth"); }
		}

		///<summary>
		/// Text Color
		///</summary>
		[ImplementPropertyType("textColor")]
		public string TextColor
		{
			get { return this.GetPropertyValue<string>("textColor"); }
		}
	}
}
