//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Site Settings</summary>
	[PublishedContentModel("siteSettings")]
	public partial class SiteSettings : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "siteSettings";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SiteSettings(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SiteSettings, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Base Page Title
		///</summary>
		[ImplementPropertyType("basePageTitle")]
		public string BasePageTitle
		{
			get { return this.GetPropertyValue<string>("basePageTitle"); }
		}

		///<summary>
		/// Contact Email
		///</summary>
		[ImplementPropertyType("contactEmail")]
		public string ContactEmail
		{
			get { return this.GetPropertyValue<string>("contactEmail"); }
		}

		///<summary>
		/// Contact Phone
		///</summary>
		[ImplementPropertyType("contactPhone")]
		public string ContactPhone
		{
			get { return this.GetPropertyValue<string>("contactPhone"); }
		}

		///<summary>
		/// Default Details Background Color
		///</summary>
		[ImplementPropertyType("defaultDetailsBackgroundColor")]
		public string DefaultDetailsBackgroundColor
		{
			get { return this.GetPropertyValue<string>("defaultDetailsBackgroundColor"); }
		}

		///<summary>
		/// Default Details Header Text Color
		///</summary>
		[ImplementPropertyType("defaultDetailsHeaderTextColor")]
		public string DefaultDetailsHeaderTextColor
		{
			get { return this.GetPropertyValue<string>("defaultDetailsHeaderTextColor"); }
		}

		///<summary>
		/// Default Details Text Color
		///</summary>
		[ImplementPropertyType("defaultDetailsTextColor")]
		public string DefaultDetailsTextColor
		{
			get { return this.GetPropertyValue<string>("defaultDetailsTextColor"); }
		}

		///<summary>
		/// Default Headline Background Color: Any css color (rgb, hex, name)
		///</summary>
		[ImplementPropertyType("defaultHeadlineBackgroundColor")]
		public string DefaultHeadlineBackgroundColor
		{
			get { return this.GetPropertyValue<string>("defaultHeadlineBackgroundColor"); }
		}

		///<summary>
		/// Default Headline Text Color
		///</summary>
		[ImplementPropertyType("defaultHeadlineTextColor")]
		public string DefaultHeadlineTextColor
		{
			get { return this.GetPropertyValue<string>("defaultHeadlineTextColor"); }
		}

		///<summary>
		/// Facebook: Url of facebook page.
		///</summary>
		[ImplementPropertyType("facebook")]
		public string Facebook
		{
			get { return this.GetPropertyValue<string>("facebook"); }
		}

		///<summary>
		/// Fair Housing Link
		///</summary>
		[ImplementPropertyType("fairHousingLink")]
		public string FairHousingLink
		{
			get { return this.GetPropertyValue<string>("fairHousingLink"); }
		}

		///<summary>
		/// Fair Housing Text
		///</summary>
		[ImplementPropertyType("fairHousingText")]
		public string FairHousingText
		{
			get { return this.GetPropertyValue<string>("fairHousingText"); }
		}

		///<summary>
		/// Font Color: Hex code (#a12b39)
		///</summary>
		[ImplementPropertyType("fontColor")]
		public string FontColor
		{
			get { return this.GetPropertyValue<string>("fontColor"); }
		}

		///<summary>
		/// Image
		///</summary>
		[ImplementPropertyType("image")]
		public IPublishedContent Image
		{
			get { return this.GetPropertyValue<IPublishedContent>("image"); }
		}

		///<summary>
		/// Instagram: Url of instagram page.
		///</summary>
		[ImplementPropertyType("instagram")]
		public string Instagram
		{
			get { return this.GetPropertyValue<string>("instagram"); }
		}

		///<summary>
		/// Legal Links
		///</summary>
		[ImplementPropertyType("legalLinks")]
		public IPublishedContent LegalLinks
		{
			get { return this.GetPropertyValue<IPublishedContent>("legalLinks"); }
		}

		///<summary>
		/// LinkedIn: Url of LinkedIn page
		///</summary>
		[ImplementPropertyType("linkedIn")]
		public string LinkedIn
		{
			get { return this.GetPropertyValue<string>("linkedIn"); }
		}

		///<summary>
		/// Meta Tags
		///</summary>
		[ImplementPropertyType("metaTags")]
		public IPublishedContent MetaTags
		{
			get { return this.GetPropertyValue<IPublishedContent>("metaTags"); }
		}

		///<summary>
		/// Twitter: Url of twitter page.
		///</summary>
		[ImplementPropertyType("twitter")]
		public string Twitter
		{
			get { return this.GetPropertyValue<string>("twitter"); }
		}
	}
}
