//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Site</summary>
	[PublishedContentModel("site")]
	public partial class Site : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "site";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Site(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Site, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Content Items Folder
		///</summary>
		[ImplementPropertyType("contentItemsFolder")]
		public IEnumerable<IPublishedContent> ContentItemsFolder
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("contentItemsFolder"); }
		}

		///<summary>
		/// Footer
		///</summary>
		[ImplementPropertyType("footer")]
		public IEnumerable<IPublishedContent> Footer
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("footer"); }
		}

		///<summary>
		/// Navigation Bar
		///</summary>
		[ImplementPropertyType("navigationBar")]
		public IEnumerable<IPublishedContent> NavigationBar
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("navigationBar"); }
		}

		///<summary>
		/// Site Settings
		///</summary>
		[ImplementPropertyType("siteSettings")]
		public IEnumerable<IPublishedContent> SiteSettings
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("siteSettings"); }
		}
	}
}
