//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Slide with Custom Stats</summary>
	[PublishedContentModel("slideWithCustomStats")]
	public partial class SlideWithCustomStats : Slide
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "slideWithCustomStats";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SlideWithCustomStats(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SlideWithCustomStats, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Background Color
		///</summary>
		[ImplementPropertyType("backgroundColor")]
		public string BackgroundColor
		{
			get { return this.GetPropertyValue<string>("backgroundColor"); }
		}

		///<summary>
		/// Border Color
		///</summary>
		[ImplementPropertyType("borderColor")]
		public string BorderColor
		{
			get { return this.GetPropertyValue<string>("borderColor"); }
		}

		///<summary>
		/// Fill Direction
		///</summary>
		[ImplementPropertyType("fillDirection")]
		public string FillDirection
		{
			get { return this.GetPropertyValue<string>("fillDirection"); }
		}

		///<summary>
		/// Hover Background Color
		///</summary>
		[ImplementPropertyType("hoverBackgroundColor")]
		public string HoverBackgroundColor
		{
			get { return this.GetPropertyValue<string>("hoverBackgroundColor"); }
		}

		///<summary>
		/// Hover Text Color
		///</summary>
		[ImplementPropertyType("hoverTextColor")]
		public string HoverTextColor
		{
			get { return this.GetPropertyValue<string>("hoverTextColor"); }
		}

		///<summary>
		/// Link
		///</summary>
		[ImplementPropertyType("link")]
		public Umbraco.Web.Models.RelatedLinks Link
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("link"); }
		}

		///<summary>
		/// Stats Folder: Folder containing statistics
		///</summary>
		[ImplementPropertyType("statsFolder")]
		public IPublishedContent StatsFolder
		{
			get { return this.GetPropertyValue<IPublishedContent>("statsFolder"); }
		}

		///<summary>
		/// Subtitle: Subtitle under title.
		///</summary>
		[ImplementPropertyType("subtitle")]
		public string Subtitle
		{
			get { return this.GetPropertyValue<string>("subtitle"); }
		}

		///<summary>
		/// Text Color
		///</summary>
		[ImplementPropertyType("textColor")]
		public string TextColor
		{
			get { return this.GetPropertyValue<string>("textColor"); }
		}

		///<summary>
		/// Text Color Button
		///</summary>
		[ImplementPropertyType("textColorButton")]
		public string TextColorButton
		{
			get { return this.GetPropertyValue<string>("textColorButton"); }
		}

		///<summary>
		/// Title: Title at top of slide.
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}

		///<summary>
		/// Title Text Color
		///</summary>
		[ImplementPropertyType("titleTextColor")]
		public string TitleTextColor
		{
			get { return this.GetPropertyValue<string>("titleTextColor"); }
		}
	}
}
