//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Slide Stat</summary>
	[PublishedContentModel("slideStat")]
	public partial class SlideStat : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "slideStat";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SlideStat(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SlideStat, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Image: Overrides Text
		///</summary>
		[ImplementPropertyType("image")]
		public IPublishedContent Image
		{
			get { return this.GetPropertyValue<IPublishedContent>("image"); }
		}

		///<summary>
		/// Image alt text
		///</summary>
		[ImplementPropertyType("imageAltText")]
		public string ImageAltText
		{
			get { return this.GetPropertyValue<string>("imageAltText"); }
		}

		///<summary>
		/// Text Line 1
		///</summary>
		[ImplementPropertyType("textLine1")]
		public string TextLine1
		{
			get { return this.GetPropertyValue<string>("textLine1"); }
		}

		///<summary>
		/// Text Line 1: big: Big text or small text
		///</summary>
		[ImplementPropertyType("textLine1Big")]
		public bool TextLine1Big
		{
			get { return this.GetPropertyValue<bool>("textLine1Big"); }
		}

		///<summary>
		/// Text Line 2
		///</summary>
		[ImplementPropertyType("textLine2")]
		public string TextLine2
		{
			get { return this.GetPropertyValue<string>("textLine2"); }
		}

		///<summary>
		/// Text Line 2: big: Big text or small text
		///</summary>
		[ImplementPropertyType("textLine2Big")]
		public bool TextLine2Big
		{
			get { return this.GetPropertyValue<bool>("textLine2Big"); }
		}
	}
}
