//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Sub Nav</summary>
	[PublishedContentModel("subNav")]
	public partial class SubNav : PublishedContentModel, INavElement
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "subNav";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SubNav(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SubNav, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Always show color?: default will show on hover
		///</summary>
		[ImplementPropertyType("alwaysShowColor")]
		public bool AlwaysShowColor
		{
			get { return Umbraco.Web.PublishedContentModels.NavElement.GetAlwaysShowColor(this); }
		}

		///<summary>
		/// Color
		///</summary>
		[ImplementPropertyType("color")]
		public string Color
		{
			get { return Umbraco.Web.PublishedContentModels.NavElement.GetColor(this); }
		}

		///<summary>
		/// Display Name: Will be displayed in nav bar instead of page name.
		///</summary>
		[ImplementPropertyType("displayName")]
		public string DisplayName
		{
			get { return Umbraco.Web.PublishedContentModels.NavElement.GetDisplayName(this); }
		}

		///<summary>
		/// Page
		///</summary>
		[ImplementPropertyType("page")]
		public IPublishedContent Page
		{
			get { return Umbraco.Web.PublishedContentModels.NavElement.GetPage(this); }
		}
	}
}
